name: "Akeda Bagus's Website"
author: "Akeda Bagus"
email: "admin@gedex.web.id"
description: "Web developer from Indonesia"
url: "http://gedex.github.io"

# posts per page
paginate: 10

# number of items in feed
feed_limit: 10

# permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

# commenting widget
disqus:
  shortname: 'akeda'

feedburner: 'akedabagus'

#google analytics username
ga_username: 'UA-2410626-1'

#build config
markdown: kramdown
pygments: true
